apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: big-mens
  namespace: flux-system
spec:
  image: ghcr.io/lukeanderson93/big-mens
  interval: 1m
  secretRef:
    name: github-container-registry-credentials
