apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: big-mens
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: big-mens
  policy:
    semver:
      range: ">=0.0.0"
