# https://taskfile.dev

version: "3"

tasks:
  logs:
    cmds:
      - flux logs --follow --all-namespaces

  reconcile:
    cmd: flux reconcile kustomization flux-system --with-source

  # there's probably a better way to do this, but I am still learning, so this seems to work!
  reconcile-homeassistant:
    cmd: flux reconcile helmrelease homeassistant -n home-assistant
