# https://taskfile.dev

version: "3"

tasks:
  logs:
    cmds:
      - flux logs --follow --all-namespaces

  reconcile:
    cmds:
      - flux reconcile kustomization flux-system --with-source
      - flux reconcile helmrelease homeassistant -n home-assistant

  info:
    cmds:
      - flux get helmreleases -A
      - flux get sources git -A
      - flux get sources helm -A
      - flux get kustomizations -A

  check:
    cmds:
      - flux check --pre
      - flux check

  uninstall-homeassistant:
    cmds:
      - helm uninstall homeassistant -n home-assistant