# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: List all commands.
    cmds:
      - task --list-all

  logs:
    desc: Flux logs.
    cmds:
      - flux logs --follow --all-namespaces

  reconcile:
    desc: Reconcile flux.
    cmds:
      - flux reconcile kustomization flux-system --with-source
      - flux reconcile helmrelease homeassistant -n home-assistant

  info:
    desc: Get some info from flux.
    cmds:
      - flux get helmreleases -A
      - flux get sources git -A
      - flux get sources helm -A
      - flux get kustomizations -A

  check:
    desc: Run flux checks.
    cmds:
      - flux check --pre
      - flux check

  uninstall-homeassistant:
    desc: Uninstall homeassistant.
    cmds:
      - helm uninstall homeassistant -n home-assistant

  kubeseal-install:
    desc: "Install kubeseal on mac"
    cmds:
      - brew install kubeseal

  kubeseal-export-pub-key:
    desc: "Export public key from kubeseal"
    cmds:
      - >
        kubectl get secret \
          --namespace flux-system \
          --selector sealedsecrets.bitnami.com/sealed-secrets-key=active \
          --output jsonpath='{.items[0].data.tls\.crt}' \
        | base64 -d > pub-sealed-secrets.pem
