---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-container-registry-credentials
  namespace: flux-big-mens-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAMlJpjt/k6jDepGrlW1lEoGoh5B3hA4FbILEQHLKvRy//C7dXT5PYe58lb8OA/yiMryprnKpdBnoo1xXOu2LwHERmJW1MCX1yuSqbvEOfBdTyCjD5gSqyjha3IknP/H/Cmckz7tIIl5b8CgkKQCdi2plEz5CFdce8pJyXuu1RAjpt+Cmfk1L8c+kxrbtB+lGaQJBAQdpNShtfRw+ueA1RbshI5LwTD1aMJqLC4T7tbrba4Bqo4CiRRHtePMrh95fs6sgTuRJb2o3FxXjcxmn0zRhan444XaAs4UaDSZANGO+f7idJUioZqZkUhnRY4YkHs6PZWJdqIrqp5Y3iQO5Q7he5X7frpQrAKq1EhNI9xqUb+7gNL1q4/lZs2DMFnYngTaicUfOilVcB+nFvtwSBCrGTrimolOrM0uQrxw/bCaeGyIW+VMTOLl4/w4iCh8/H7ypG3TDLCUsUx0j71a+dEoZFmUtNJz+cbnvnDVHjG0pUALw+Or6TZqk79dfngak3IxQHt4PQbpd0sMwyBL8FGPBy8QUJkY95LOcMjovXc3zwGadHkTeRBI3UqfmkXCIrvLZ4EWcyUSl+vLejVIjT5+aRqGU5RFgbWz+eHA4y+rTzQz1/6LC4/QSWetoqvJyCfVz2WL4WSCZeQ1q1VFlT5EYgBjv1vZewFHydIalfPmokoGLvcUlmqVVP8bB9pzIQCwkhrjRJHHwI+RNhkAoxv5Yc5jAJBQV7yHsneDQ20Kiccca3JsZ/bjTIsCcSuQ1/JVRziTbx+bWCL79j5sIyZLWgWb616M6glREE7U+HWljvmh8td3vP0Ub585hfuLY/ldX66uA7vEt8dCfSCv8JVkcbtygIFcLjv9R7iIV3Vue4guuVtZUAqZxTzhtptQJhG7WE7qIaOKOM2vW2Wqr1ITpAbKtKhRvA81sQwyvCLC7miGMI+knW2R8xTC//HZA==
  template:
    metadata:
      name: github-container-registry-credentials
      namespace: flux-big-mens-dev
    type: kubernetes.io/dockerconfigjson
