apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: big-mens
  namespace: flux-big-mens-dev
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/
      sourceRef:
        kind: GitRepository
        name: big-mens-charts
        namespace: flux-system
#  values:
#    image: "ghcr.io/lukeanderson93/big-mens:0.0.4"
#    imagePullSecrets:
#      - name: github-container-registry-credentials
