apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: big-mens
  namespace: flux-big-mens-dev
spec:
  image: ghcr.io/lukeanderson93/big-mens
  interval: 1m
  secretRef:
    name: ghcr-credentials
