apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - namespace.yaml
  - discord-token-secret-sealed.yaml
  - github-container-registry-credentials-sealed.yaml
  - helmrelease.yaml
