---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-token-secret
  namespace: flux-big-mens-prod
spec:
  encryptedData:
    token: AgAl9/FdsPexUdbAxu7VJ87GeGjg8YwKdOjdgVbSVsyAa8APuIL5L3GD2CM8gTxFvH6MxAQccg1YAppQvF7KT/k9LP2/hDlKRFh8tEeB4R+Kj2X+bumw1zuZyYzd9+7SifJuIALHsVbVUafz/3VPDARn1V3ih0nkLqKquHaYM2hkCncyr58tmplQCPh40ehtaQmhxvVvPNSxsK/x0lfd4hlU5+pRtb3CjOImzHdu1RYNjPY0F4sYspMfmJI1Cg8iJw7rYJpf9em92vz/+bpjJbnnDqQbVNj07ycoxIY0r00alMkuVKhdcVJcEixmemfBT23YW6Wq5kn8j8g/YcRuo4T4xp1CPpfzsAC1IWTJ3YuXFc2chOHbTLmQboLmZuDhR1VzNGa91GcxnY6N+cw/6qd7SsxS86Dcipojs8otRSIF2BK2KV/SAn9iPf18TkQYkfdGhAw0WWP7DzLSVeUvmcuNVrgDWyJKaUjxdT+s5lW6JvNnqyG8sXHQwW6LaVsBhtW8t/a0Fxkhcz8jziFp7X28WzFmb9rhvs9SWgIeEe/SBlqzUCefD18hkHb3jOrERw3ZDLj+aqTCXUTKnbnGsWWNEHFQfRGxcQLKtQwjESWs5Ki0Kq2le6Ow67bKZiJRSJZZQIgCj1J1X6ypHpZfG+onaAY8P7m5ntRdL78r6+KQnv75JA9UCX0dvI7q8QZWlKn8wbPQxRZk/Yha47ytTSED+fx8rv0AkZAtllH00OmQqkdgJi2QYVthKtxPEH/Dv+Y0CTeHRoOAWcXXRAqhaVaWUxXyKBROFGA=
  template:
    metadata:
      name: discord-token-secret
      namespace: flux-big-mens-prod
