---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-token-secret
  namespace: flux-big-mens-prod
spec:
  encryptedData:
    token: AgCbUFg1IgDue+FyvKq5DoFp669TAzpszIvkIvW9y8jWDF1ypLedm8ddwiKsdDcb0lePLI7n9lr0S+nznMkpjfYdzc1gDDY1nb20Wn5Q83telkZwJLikh8gbefhYQrJv7JqYwMD44Xk/sy3/V4lthNzRLOgaiKljKWBnj1xg51ijJQFz8Bj4S2BY/0gmQwBweNd5xt5UfakKZRLq15oCx86u6jDSSRsFvPZNsOUtI8NUKVUxWDfzvhIx9SHGnx8HmMqc+1QwKzGWMRyImsUobjfcUBHwXIURZpQnPEPPwHd1mFn0IwThHPHMjsRph8Tl8fYaHO1Nk4rn0Z6R38jjxWUYG1yiBfGnqXB0RvRdmzvYMTp16SQQMiyRrNq++wyV9OrhJ0ZYoEGsgjNCNydx/C7QN89ED7V0XLH9uTE83iWLIGv4RPWIr/OWpoTd23tPL0cbxSmzaIkxPXi3FV0F+VNtt7N66cYAd5LCtXvv7Xhez2Lo+U0uMpB4SFAtLB9+wYy4WNHynCEhHl9JwmRqqBYVSRS25KVjdOqivvun7LOP2ABzfER1YrgL4iMXQTKUwEf8j6siydPMW622fpjZXHREyOpSyl0BzOjpmoVSjPCAYsrhLs4kmONjyoNIXpy/ObvH360583Sw7aHMxNVBCISw7oenbbvJbHL2Mv7PSnqk1cw9FA6qnH3P81CnvZnGXI0=
  template:
    metadata:
      name: discord-token-secret
      namespace: flux-big-mens-prod
