apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: homeassistant-charts
  namespace: home-assistant
spec:
  interval: 1h
  url: https://pajikos.github.io/home-assistant-helm-chart/
