apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: flux-homeassistant
spec:
  interval: 10m
  chart:
    spec:
      chart: home-assistant
      version: 0.3.16
      sourceRef:
        kind: HelmRepository
        name: homeassistant-charts
        namespace: flux-homeassistant
  values:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: ""
#      existingClaim: ""

    configuration:
      enabled: true

    ingress:
      enabled: true
      hosts:
        - host: flux-homeassistant.k8s.lukeanderson.co.uk
          paths:
            - path: /
              pathType: ImplementationSpecific
