apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: home-assistant
spec:
  interval: 10m
  chart:
    spec:
      chart: home-assistant
      version: 0.3.16
      sourceRef:
        kind: HelmRepository
        name: homeassistant-charts
        namespace: home-assistant
  values:
    persistence:
      enabled: true
      # using existingClaim only works in deployment mode, not sure why, there's probably some good reason.
      # just need to "unlink" the pv from the pvc by deleting the pvc with pv as retain.
      existingVolume: "pvc-7a707d26-684c-498d-9cbb-4033eeaf67fe"

    configuration:
      enabled: false

    ingress:
      enabled: true
      hosts:
        - host: homeassistant.k8s.internal
          paths:
            - path: /
              pathType: ImplementationSpecific
