---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: big-mens-helmrelease-alert
  namespace: flux-system
spec:
  providerRef:
    name: discord-dev-server
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: big-mens
      namespace: flux-big-mens-prod
