---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord-dev-server
  namespace: flux-system
spec:
  type: discord
  secretRef:
    name: discord-webhook-dev-server-secret
