apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
      version: ">=v1.16.2"
  interval: 1h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
