---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-container-registry-credentials
  namespace: flux-big-mens-dev
spec:
  encryptedData:
    .dockerconfigjson: AgATx9PvNbYlTpI0d8ZGfKdMwly1vIPqHNTngyX61Umd0nBL3s3+elM89WZ1GB6xh+7XNDmJmGTZx7KcZqXoIisXWPEMSPKpM9eB9I3JwkFEV1ZBJCImr0GFekH9J+sEbCoEiHIAUxD2JBkRPqGzsZB4eNRd4d0lQQCKpdNWbecIAvC/pTn4+M3oSh9zroXeSpUgDeCSPFvdhaNuG1Km0cpMt8y0sr6onQw0OF2uw6nqbogi4BGgYA5915jXSFsqwolIhkUCz8c6oTI9FenCi+5nosJu/x614QRIQAfumqwRTul6F/71I+W/lEHzqZ6fVoIILHL+90Rt7h8TIDT9X8P6lG9Pk7T5GHQOHC754PieLuBUwMqMBxbU86tfHUHp+FwA5xzp7svyTQYkh1dey6z+Xu5T6i+NmyZtiMtjb7KyWRNWKOFy0RpVc/OP0cpyo7kQ1k6FvAR71qob+bgvV1bLF+HP6vwbtEmNoXs6ZHveMmQGq7P/0rwRJI3bCSIFTb/MbpEKzR2sakJava8Cqn4gUYVAGGN/MGT+HALbDDz8puvCZzP2CRkxCGeBxlAu1FS+rnNDh7z6O5/d6fuqZYb1hD18v6HislRKK+GZ0s2S4M1ZhQkJhZNIq7F3AtvLuyxtJdtasSBigKlB5Fnfj/1XVY3JrFElj8wtzwalhtkQ5vQRgLXnnnzuSUbbaMxoCUHCz9jlACJ0eBTpVbfnzG9mrw1DP7eWj1tTkE1hNMV28dWnOjqJFEWe2raLw24ZYlaTsEkxXCetEwJtNQdgX0BzGtj3kW3LokgUS2bj8quzUe4UQRvdtwKry0YwcJTPcQsoCqj1tZawUrVeLgRMBKZaoHZRkqVUFDp4/zmYjLBKZ/Z4odmtjEUmTFp4eTXJ9F/OhJfFhcbMDswrKa7dS/OBVq7Ft/RDKYsoVFYCbvFZw7rsjVULf8YVQwcN8TJ1Eg==
  template:
    metadata:
      name: github-container-registry-credentials
      namespace: flux-big-mens-dev
    type: kubernetes.io/dockerconfigjson
