apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: big-mens
  namespace: flux-big-mens-dev
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/
      sourceRef:
        kind: GitRepository
        name: big-mens-charts
        namespace: flux-system
  values:
    imagePullSecrets:
      - name: github-container-registry-credentials
    image: "ghcr.io/lukeanderson93/big-mens:0.0.16" # {"$imagepolicy": "flux-system:big-mens"}
    bigBotEnvironment: "development"
    discord:
      bigMensRoleId: "1004746165251747902"
      roleAssignmentChannelId: "1001933604491898933"
      shootingStarsChannelId: "1320029240346808360"
      twitchLiveChannelId: "1320345642165473300"
    pgweb:
      ingress:
        enabled: true
        className: traefik
        hosts:
          - host: dev-pgweb.bigbot.k8s.lukeanderson.co.uk
            paths:
              - path: /
                pathType: Prefix
      env:
        - name: PGWEB_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: pgweb-database-url-secret
              key: PGWEB_DATABASE_URL
    postgresql:
      auth:
        database: bigmens
        username: bigmens
        password: bigmens
